#!/usr/bin/env python

import os
import re

sanitize_cvar = re.compile(r"[.,-]")

def bin2h_task(bld, src, dst, var=None):
	if not var:
		var = sanitize_cvar.sub("_", os.path.basename(src)).upper()

	bld(
		rule="python ../python/bin2h.py -p static -v %s < ${SRC} > ${TGT}" % var,
		source="{0}".format(src),
		target="{0}".format(dst),
		name="assets",
		export_includes=".",
		update_outputs=True)

def css2c_task(bld, src, dst):
	bld(
		rule="python ../python/css2c.py < ${SRC} > ${TGT}",
		source="{0}".format(src),
		target="{0}".format(dst),
		name="assets",
		export_includes=".",
		update_outputs=True)


def build(bld):
	asset = lambda src, dst: bin2h_task(bld, src, dst)
	stylesheet = lambda src, dst: css2c_task(bld, src, dst)

	# textures

	asset("assets/tile.tga", "assets/tile.tga.h")

	# default style

	stylesheet("style.css", "definition.h")
