#!/usr/bin/env python

from waflib.TaskGen import after_method, before_method, feature

top = '..'

def build(bld):
    def example(tgt, extra_use=[]):
        bld.program(
                source='{}.c'.format(tgt),
                use=['rutabaga', 'rtb_style_default'] + extra_use,
                target=tgt)

    example('test')
    example('basic')
    example('txtest')
    example('tiny')

    if bld.env.LIB_JACK:
        example('cabbage_patch', ['JACK'])
