#!/usr/bin/env python

def build(bld):
    styles = []
    style = lambda s: styles.append(s)

    style("default")

    for s in styles:
        bld.rtb_style(s)

    bld(
        use=["style_{0}".format(s) for s in styles],
        target="styles")
